schema_version = "1.0.0"

id = "node_editor_switcher"
version = "1.0.3"
name = "Node Editor Switcher"
tagline = "Pie menu, shortcuts and buttons to switch between node editors"
maintainer = "Victor Chedeville <victor.ched@gmail.com>"
type = "add-on"

website = "https://github.com/Victor-IX/NodeEditorSwitcher"

tags = [
  "Node", "Pipeline", "User Interface"
]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

copyright = [
  "2023-2024 Victor Chedeville",
]